DROP TABLE IF EXISTS `#__listmanager_access`;
DROP TABLE IF EXISTS `#__listmanager_listing`;
DROP TABLE IF EXISTS `#__listmanager_field`;
DROP TABLE IF EXISTS `#__listmanager_values`;
DROP TABLE IF EXISTS `#__listmanager_acl`;
DROP TABLE IF EXISTS `#__listmanager_view`;
DROP TABLE IF EXISTS `#__listmanager_field_view`;
DROP TABLE IF EXISTS `#__listmanager_rate`;
DROP TABLE IF EXISTS `#__listmanager_field_multivalue`;
